### ISSUE TITLE
Return non-zero exit code upon test failure

### ISSUE THREAD

**Issue by jeremyhiggs** [nawforce/ApexLink#1]
Some tests failed in a run:
> 76 tests have failed of 2413 run after 7 minutes                                                                           
> parallel Test run completed at Friday, October 18, 2019 7:32 AM                                                            
> Of 2413 tests run, 76 have failed :-(                                                                                      
> Review test-report.json for failure details                                                                                
> Finished at Friday, October 18, 2019 7:32 AM, took 7 minutes            

However, I noticed that the exit code was 0, because the CI build was reported to have passed! It would be much better if this was non-zero (or better yet, followed the behaviour sfdx test).

**Comment by nawforce** [comment]
Thanks for reporting this. I have put a fix in for this that will give status code 1 if there are oustanding failures.

I was planning on adding automatic test selection to this (based on dependency analysis) which I thought might be difficult to fit to the force:apex:test:run/force:apex:test:report model but maybe it's possible by having a pair of command, will take a look at that.

**Comment by jeremyhiggs** [comment]
Thank you!

I also noticed that the output file for tests is different to the error
message output. test-result.json vs test-report.json IIRC


On 22 October 2019 at 2:07:37 AM, Kevin Jones (notifications@github.com)
wrote:

Thanks for reporting this. I have put a fix in for this that will give
status code 1 if there are oustanding failures.

I was planning on adding automatic test selection to this (based on
dependency analysis) which I thought might be difficult to fit to the
force:apex:test:run/force:apex:test:report model but maybe it's possible by
having a pair of command, will take a look at that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nawforce/ApexLink/issues/1?email_source=notifications&email_token=AABMPUDHCLL7XMYU7A5FXXTQPYKZRA5CNFSM4JCEELM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB3ZNJQ#issuecomment-544708262>,
or unsubscribe

**Comment by nawforce** [comment]
Thanks, I have corrected that.
