### ISSUE TITLE
Several standard objects not recognized

### ISSUE THREAD

**Issue by JmeG** [nawforce/ApexLink#4]
No type declaration found for 'ObjectTerritory2Association'
No type declaration found for 'Territory2'
No type declaration found for 'Territory2Type'
No type declaration found for 'Territory2Model'
No type declaration found for 'UserTerritory2Association'

No type declaration found for 'OpportunityTeamMember'
No type declaration found for 'OpportunitySplitType'
No type declaration found for 'OpportunitySplit'

**Comment by nawforce** [comment]
Thanks for raising this and others. I have updated SObjects to Winter '20 (they were a little behind) and selected right org options to make these visible.
